version: "3.8"

services:
  test_app:
    build:
      context: app
    container_name: test_avito_test_api
    environment:
      DB_HOST: 'test_avito_test_db'
    command: sh -c "sleep 5
                    && pip install pytest pytest-cov
                    && pytest --cov-config=app/tests/.coveragerc --cov=app app/tests --ignore=app/tests/load_test.py"
    depends_on:
      - test_db

  test_db:
    build: db/
    container_name: test_avito_test_db
