version: "3.8"

services:
  app:
    build:
      context: app
    container_name: avito_test_api
    environment:
      DB_HOST: 'avito_test_db'
    depends_on:
      - db
    ports:
      - 8000:8000
    restart: always

  db:
    build: db/
    container_name: avito_test_db
